theme = ["blowfish", "hugo-shortcodes"]
baseURL = "https://www.gamedevhobby.com/"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0
buildDrafts = false
buildFuture = false
enableEmoji = true
googleAnalytics = "G-W5GDJWS1JT"
timeout = "600s"

[pagination]
pagerSize = 100

[imaging]
anchor = "Center"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = "daily"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[related]
threshold = 0
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 100

  [[related.indices]]
  name = "series"
  weight = 50

  [[related.indices]]
  name = "authors"
  weight = 20

  [[related.indices]]
  name = "date"
  weight = 10

  [[related.indices]]
  applyFilter = false
  name = "fragmentrefs"
  type = "fragments"
  weight = 10
