disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "GameDevHobby"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo-icon.png"
description = "Welcome to GameDevHobby! I’m an indie developer focused on building engaging, atmospheric games - mostly in Unity and occasionally in Godot. I started game dev as a hobby, but over time it turned into a passion project that refuses to let go. This site is a devlog for my projects, a place to share my process, and an evolving portfolio of everything I’ve built (or broken)."

[[params.author.links]]
github = "https://github.com/GameDevHobby/"
itch-io = "https://gamedevhobby.itch.io/"

["params.author"]
name = "Chris Gheen"
image = "Avatar.png"
headline = "A solo developer building sci-fi roguelikes, weird experiments, and everything in between. I use Unity, Godot, and too many coffee breaks. This blog documents my development process, design challenges, and the occasional game dev success story."
