[[main]]
none = "none"

[[main]]
name = "Devlog"
pageRef = "posts"
identifier = "0hjlszb7ew"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "xjRVfDGMRz"
weight = 9_999

[[main]]

[[footer]]
none = "none"

[[footer]]
name = "Topics"
pageRef = "topics"
identifier = "2ntessdAmC"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "pages/privacy-policy"
identifier = "2bU7tnEOR3"
weight = 15
